control@control:~/a$ vim r.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: namespace1
  name: user1-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments", "services", "replicationcontrollers", "replicasets", "daemonsets", "statefulsets", "horizontalpodautoscalers", "cronjobs", "jobs"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-binding
  namespace: namespace1
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user1-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: namespace2
  name: user2-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments", "services", "replicationcontrollers", "replicasets", "daemonsets", "statefulsets", "horizontalpodautoscalers", "cronjobs", "jobs"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user2-binding
  namespace: namespace2
subjects:
- kind: User
  name: user2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user2-role
  apiGroup: rbac.authorization.k8s.io
