apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: namespace2
  name: user2-role
rules:
- apiGroups: [""]
  resources: ["pods", "events"]  # Add events here
  verbs: ["list", "get", "watch"]
